[book]
authors = ["Ticiano Morvan"]
language = "es"
multilingual = false
src = "src"
title = "FAMAF - LCC"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
mathjax-support = true
